### ISSUE TITLE
help me pls:(((

### ISSUE THREAD

**Issue by baodz1805** [weibes/dactyl-config#1]
I'm having a problem with my dacytl firmware and I'm looking for a solution. I went through your post and the error you encountered yesterday is the same as mine. I read through your code when I finished it and I don't know where the problem is. copy and it's still the same. Can you tell me what you did to resolve it?

**Comment by baodz1805** [comment]
https://github.com/baodz1805/zmk-config./actions/runs/9273653637 you can check out

**Comment by weibes** [comment]
Hi baodz,

I fixed your repo and put it as a repo of my own, check here:
https://github.com/weibes/test-zmk-config/actions/runs/9273656618

The issue was that your dactyl config files were not in their own file, they were just in boards/shields. I moved them to boards/shields/dactyl, and they worked perfectly. You can find the documentation [here](https://zmk.dev/docs/development/new-shield), and go down to where it says "New Shield Directory".

FYI, I think ZMK will also require that we move the directory from boards/shields/dactyl to app/boards/shields/dactyl/ . The docs are saying it'll happen "some time in the future", which given its nebulous nature, I have no idea when that'll happen.

Hope this helps :)

-weibes

**Comment by baodz1805** [comment]
omg i love you so much thanks everything ,I spent 4 hours fixing it over
and over again

[image: Biểu tượng Cộng đồng đã xác minh]


Vào Th 4, 29 thg 5, 2024 vào lúc 00:27 Brendan ***@***.***>
đã viết:
